
package com.bajajalianz.insurance.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.bajajalianz.insurance.types.Member;
import com.bajajalianz.insurance.types.ObjectFactory;
import com.bajajalianz.insurance.types.Plan;
import com.bajajalianz.insurance.types.Policy;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "insurance", targetNamespace = "http://www.bajajalianz.com/insurance/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Insurance {


    /**
     * 
     * @param member
     * @param plan
     * @return
     *     returns com.bajajalianz.insurance.types.Policy
     */
    @WebMethod(action = "http://www.bajajalianz.com/insurance/services/enroll")
    @WebResult(name = "policy", targetNamespace = "http://www.bajajalianz.com/insurance/types")
    @RequestWrapper(localName = "enroll", targetNamespace = "http://www.bajajalianz.com/insurance/types", className = "com.bajajalianz.insurance.types.Enroll")
    @ResponseWrapper(localName = "enrollResponse", targetNamespace = "http://www.bajajalianz.com/insurance/types", className = "com.bajajalianz.insurance.types.EnrollResponse")
    public Policy enroll(
        @WebParam(name = "plan", targetNamespace = "http://www.bajajalianz.com/insurance/types")
        Plan plan,
        @WebParam(name = "member", targetNamespace = "http://www.bajajalianz.com/insurance/types")
        Member member);

}
