
package in.airtel.recharge.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import in.airtel.recharge.types.ObjectFactory;
import in.airtel.recharge.types.Receipt;
import in.airtel.recharge.types.RechargeInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AirtelRechargeService", targetNamespace = "http://www.airtel.in/recharge/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AirtelRechargeService {


    /**
     * 
     * @param in
     * @return
     *     returns in.airtel.recharge.types.Receipt
     * @throws InvailidMobileNumberFaultException
     * @throws PlanNotFoundFaultException
     */
    @WebMethod(action = "http://www.airtel.in/recharge/services/recharge")
    @WebResult(name = "receipt", targetNamespace = "http://www.airtel.in/recharge/types", partName = "out")
    public Receipt recharge(
        @WebParam(name = "recharge-info", targetNamespace = "http://www.airtel.in/recharge/types", partName = "in")
        RechargeInfo in)
        throws InvailidMobileNumberFaultException, PlanNotFoundFaultException
    ;

}
