
package in.airtel.recharge.services;

import javax.xml.ws.WebFault;
import in.airtel.recharge.types.Error;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "error", targetNamespace = "http://www.airtel.in/recharge/types")
public class PlanNotFoundFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Error faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PlanNotFoundFaultException(String message, Error faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PlanNotFoundFaultException(String message, Error faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: in.airtel.recharge.types.Error
     */
    public Error getFaultInfo() {
        return faultInfo;
    }

}
